Update gate jobs as per the 2025.1 cycle testing runtime
As per 2025.1 testing runtime[1], we need to test on Ubuntu
Noble and python 3.9 to 3.12.

Also fixing the memoryview error
   AttributeError: 'memoryview' object has no attribute 'decode'

Tracking: https://etherpad.opendev.org/p/migrate-to-noble

[1] https://governance.openstack.org/tc/reference/runtimes/2025.1.html

Change-Id: Idf0f211043c13c6b96f40fcf2891e84d5959fdb6